server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: Capper636.
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 3
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    # rabbitmq配置
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          multiplier: 2
          max-attempts: 5
          initial-interval: 1000ms
          max-interval: 2000ms
        acknowledge-mode: auto
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug